"""'Initial'

Revision ID: d21160e6d664
Revises: 
Create Date: 2020-08-23 14:35:15.964860

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd21160e6d664'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('semesters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('courses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.String(), nullable=True),
    sa.Column('course_title', sa.String(length=64), nullable=True),
    sa.Column('description', sa.String(length=64), nullable=True),
    sa.Column('vid_title1', sa.String(length=64), nullable=True),
    sa.Column('vid_desc1', sa.String(length=64), nullable=True),
    sa.Column('vid_title2', sa.String(length=64), nullable=True),
    sa.Column('vid_desc2', sa.String(length=64), nullable=True),
    sa.Column('resc_title1', sa.String(length=64), nullable=True),
    sa.Column('resc_desc1', sa.String(length=64), nullable=True),
    sa.Column('resc_title2', sa.String(length=64), nullable=True),
    sa.Column('resc_desc2', sa.String(length=64), nullable=True),
    sa.Column('resc_title3', sa.String(length=64), nullable=True),
    sa.Column('resc_desc3', sa.String(length=64), nullable=True),
    sa.Column('vid_link1', sa.String(length=64), nullable=True),
    sa.Column('vid_link2', sa.String(length=64), nullable=True),
    sa.Column('resc_link1', sa.String(length=64), nullable=True),
    sa.Column('resc_link2', sa.String(length=64), nullable=True),
    sa.Column('resc_link3', sa.String(length=64), nullable=True),
    sa.Column('mit_link', sa.String(length=64), nullable=True),
    sa.Column('semester_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['semester_id'], ['semesters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_courses_course_id'), 'courses', ['course_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_courses_course_id'), table_name='courses')
    op.drop_table('courses')
    op.drop_table('semesters')
    # ### end Alembic commands ###
